(print (if (= 5 10) "true" "false"))
(print " ")
(print (if (!= 5 10) "true" "false"))
(print " ")
(print (if (< 5 10) "true" "false"))
(print " ")
(print (if (> 5 10) "true" "false"))
(print " ")
(print (if (<= 5 10) "true" "false"))
(print " ")
(print (if (>= 5 10) "true" "false"))
